### ISSUE TITLE
Images are being rotated by the Media Browser

### ISSUE THREAD

**Issue by AaronDB2** [Sterc/revolution#23]
Sometimes an image is being rotated by the Media Browser after uploading

**Comment by Heibelshoppen** [comment]
![Schermafbeelding 2021-02-26 om 09 08 18](https://user-images.githubusercontent.com/79689999/109273696-d3050c80-7812-11eb-80b7-0b8d6f283a71.png)

These are portrait photos that are then displayed landscape in the media browser.

**Comment by gpsietzema** [comment]
@Heibelshoppen can you share that specific image?

**Comment by Heibelshoppen** [comment]
Same problem with this image. 
![Schermafbeelding 2021-03-01 om 11 07 44](https://user-images.githubusercontent.com/79689999/109482522-62fabe80-7a7e-11eb-9209-ea9d5700f7a5.png)
![20190627_102248 1](https://user-images.githubusercontent.com/79689999/109482539-6b52f980-7a7e-11eb-876a-4eb0c59c3ae1.jpg)

**Comment by gpsietzema** [comment]
This issue is part of the '21 MODX SnowUp/BugHunt and has a bounty on it (https://vi.to/hubs/modx-meetup).

Requirements:
1. A pull request to github.com/Sterc/revolution
2. (Optional - if possible without modifications) A pull request to github.com/modxcms/revolution
3. Clear description of what was wrong and how you fixed it

**Comment by theuros** [comment]
I had same problem with some images and problem I think is is how image orientation is defined in image meta data. Probably media browser doesn't reckognize the defined orientation. Usually if you open that image in photoshop and save it again, then it will work (sadly this is not a fix for the client).

**Comment by ilyautkin** [comment]
I'm going to work on this
