### ISSUE TITLE
SEO Suite: Default values for images and text content

### ISSUE THREAD

**Issue by AaronDB2** [Sterc/revolution#26]
See this issue: https://github.com/Sterc/seosuite/issues/9

**Comment by gpsietzema** [comment]
This issue is part of the '21 MODX SnowUp/BugHunt and has a bounty on it (https://vi.to/hubs/modx-meetup).

Requirements:
1. A pull request to https://github.com/sterc/seosuite
3. Clear description of what you did

**Comment by JoshuaLuckers** [comment]
Is there more info about this issue?
