### ISSUE TITLE
Media Sources to support symlinks 

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/revolution#45]
### Summary
When adding a media source whereby the baseUrl is a Symlink, the error gets shown that Links are not supported.

### Why is it needed?
We have a multi-server environment and wish to store all uploads to one central place.

### Suggested solution(s)
I would like Media Sources to support Symlnks.
### Related issue(s)/PR(s)
None.

**Comment by gpsietzema** [comment]
Closed because it turned out to be a configuration issue.
