### ISSUE TITLE
MODX3S: Dashboard Question

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/revolution#46]
### Summary
I would like to have a standard dashboard configuration for all users. This means, I want to decide which widgets AND how wide they are.

I can lock the widgets onto the dashboard, that I have seen. But I can't find a way to decide how wide each widget should be on the dashboard. Is there a way to do this?

### Why is it needed?
I want the ability to set the sizes for optimal viewing pleasure.

### Suggested solution(s)
A setting per widget that allows me to decide how wide.

### Related issue(s)/PR(s)
None

**Comment by sonicpunk** [comment]
@ilyautkin We can close this as far as I'm concerned. I guess the standard MODX interface is enough.

**Comment by ilyautkin** [comment]
@sonicpunk ok, I'm closing
